# Generated by Django 5.0.7 on 2025-11-16 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.IntegerField(verbose_name='ID do Evento')),
                ('participante_id', models.IntegerField(verbose_name='ID do Participante')),
                ('codigo_validacao', models.CharField(default=uuid.uuid4, max_length=32, unique=True, verbose_name='Código de Validação')),
                ('participante_nome', models.CharField(max_length=255, verbose_name='Nome do Participante')),
                ('participante_email', models.EmailField(max_length=254, verbose_name='E-mail do Participante')),
                ('evento_nome', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('arquivo_pdf', models.TextField(blank=True, null=True, verbose_name='Caminho do PDF')),
                ('gerado', models.BooleanField(default=False, verbose_name='Certificado Gerado')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado por E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['evento_id'], name='certificado_evento__af520b_idx'), models.Index(fields=['participante_id'], name='certificado_partici_563eee_idx'), models.Index(fields=['codigo_validacao'], name='certificado_codigo__b719d6_idx')],
                'unique_together': {('evento_id', 'participante_id')},
            },
        ),
    ]