# Generated by Django 5.0.7 on 2025-11-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoProcessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.IntegerField(unique=True, verbose_name='ID do Evento')),
                ('evento_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Evento')),
                ('data_processamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Processamento')),
                ('total_certificados', models.IntegerField(default=0, verbose_name='Total de Certificados')),
                ('certificados_gerados', models.IntegerField(default=0, verbose_name='Certificados Gerados')),
                ('certificados_enviados', models.IntegerField(default=0, verbose_name='Certificados Enviados')),
                ('processamento_completo', models.BooleanField(default=False, verbose_name='Processamento Completo')),
            ],
            options={
                'verbose_name': 'Evento Processado',
                'verbose_name_plural': 'Eventos Processados',
                'ordering': ['-data_processamento'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.IntegerField(help_text='ID do evento no eventos-service', verbose_name='ID do Evento')),
                ('participante_id', models.IntegerField(help_text='ID do participante no inscricoes-service', verbose_name='ID do Participante')),
                ('codigo_validacao', models.CharField(help_text='Código único para validação do certificado', max_length=16, unique=True, verbose_name='Código de Validação')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Arquivo PDF')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('gerando', 'Gerando'), ('gerado', 'Gerado'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_geracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado por E-mail')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('email_destinatario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Destinatário')),
                ('tentativas_envio', models.IntegerField(default=0, verbose_name='Tentativas de Envio')),
                ('ultima_tentativa_envio', models.DateTimeField(blank=True, null=True, verbose_name='Última Tentativa de Envio')),
                ('log_erro', models.TextField(blank=True, null=True, verbose_name='Log de Erro')),
                ('evento_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Evento')),
                ('participante_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Participante')),
                ('participante_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Participante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['evento_id'], name='certificado_evento__af520b_idx'), models.Index(fields=['participante_id'], name='certificado_partici_563eee_idx'), models.Index(fields=['codigo_validacao'], name='certificado_codigo__b719d6_idx'), models.Index(fields=['status'], name='certificado_status_fb7ba4_idx'), models.Index(fields=['enviado'], name='certificado_enviado_09244d_idx')],
                'unique_together': {('evento_id', 'participante_id')},
            },
        ),
    ]
