# Generated by Django 5.0.7 on 2025-11-17 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='certificado',
            new_name='certificado_evento__11e51d_idx',
            old_name='certificado_evento__af520b_idx',
        ),
        migrations.RenameIndex(
            model_name='certificado',
            new_name='certificado_partici_a348cb_idx',
            old_name='certificado_partici_563eee_idx',
        ),
        migrations.RenameIndex(
            model_name='certificado',
            new_name='certificado_codigo__83a053_idx',
            old_name='certificado_codigo__b719d6_idx',
        ),
    ]
