# Generated by Django 5.0.7 on 2025-11-17 02:18

import apps.certificados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_rename_certificado_evento__af520b_idx_certificado_evento__11e51d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='codigo_validacao',
            field=models.CharField(default=apps.certificados.models.generate_validation_code, max_length=64, unique=True, verbose_name='Código de Validação'),
        ),
    ]
