# Generated by Django 5.0.7 on 2025-11-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_fix_codigo_validacao_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='evento_nome',
            field=models.CharField(help_text='Cache do nome - será atualizado automaticamente', max_length=255, verbose_name='Nome do Evento'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='participante_email',
            field=models.EmailField(help_text='Cache do email - será atualizado automaticamente', max_length=254, verbose_name='E-mail do Participante'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='participante_nome',
            field=models.CharField(help_text='Cache do nome - será atualizado automaticamente', max_length=255, verbose_name='Nome do Participante'),
        ),
    ]
