# Generated by Django 5.0.7 on 2025-11-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_add_template_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='enviado',
        ),
        migrations.AddField(
            model_name='certificado',
            name='disponivel_usuario',
            field=models.BooleanField(default=True, verbose_name='Disponível para Usuário'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='template_html',
            field=models.TextField(blank=True, null=True, verbose_name='Template HTML do Certificado'),
        ),
    ]
